# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/blog/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
